[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200

remappings = [
  "@layerzerolabs/devtools/=lib/devtools/",
  "@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/",
  "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
local       = "http://192.168.45.151:8545"
sepolia = "https://sepolia.infura.io/v3/86a0d6c500904bd3b7b812a46302956d"
amoy = "https://polygon-amoy.infura.io/v3/86a0d6c500904bd3b7b812a46302956d"
